feat : report3, report4 제출
beatitudo331/hanghae-java-study-12 pull request #101
Opened 2023-01-20 09:39 UTC by choincnp

2023-01-22 13:17 UTC, beatitudo331 requested changes

2023-01-22 13:17 UTC, beatitudo331 commented on src/choyoungjun/report1/Report1_3.java
> +        int x = 1;
학습자료의 두변수 바꾸기 부분 다시한번 봐주시면 좋을 것 같아요!

2023-01-22 13:17 UTC, beatitudo331 commented on src/choyoungjun/report3/Report3_10.java
> +                System.out.println("맞혔습니다.");
맞혔으니까! 종료시키는게 좋을 것 같아요ㅎㅎ break와 return 쪽을 공부하고 고민해서 적용해보세요!

2023-01-24 09:00 UTC, choincnp commented on src/choyoungjun/report3/Report3_10.java
> +                System.out.println("맞혔습니다.");
break문을 빠트렸네요 감사합니다!

2023-01-24 09:00 UTC, closed without merging