leeDoGyeong Report1 과제 완료
beatitudo331/hanghae-java-study-12 pull request #20
Opened 2023-01-18 04:14 UTC by colleenInKorea

이도경 report1 과제 완료

2023-01-18 04:22 UTC, beatitudo331 requested changes
.idea 와 .iml 과 같은 설정 파일들은 Unversioned File 로 두시고 commit 하지 말고
관리하셔서 제출할 때 는 올라오지 않게 해주세요!
아래 블로그 참고하시거나 기술매니저님들의 도움을 받아주세요!!
https://brownbears.tistory.com/477
https://hitomis.tistory.com/106

2023-01-18 05:19 UTC, colleenInKorea commented
다시 풀리퀘스트 올리면 되나요?

2023-01-18 05:25 UTC, beatitudo331 commented
> 다시 풀리퀘스트 올리면 되나요?
추가로 push하시면 반영됩니다!!
https://chanhuiseok.github.io/posts/git-3/
클로즈하고 또 올리실 필요는 없어요!!

2023-01-19 02:02 UTC, beatitudo331 commented on .gitignore
> +*.iml
추가 감사합니다!!

2023-01-19 06:36 UTC, beatitudo331 requested changes
Check plz

2023-01-19 06:36 UTC, beatitudo331 commented on src/leeDoGyeong/report2/Report2_4.java
> +        int numOfBucket = ((numOfApples/sizeOfBucket) + 1); // 모든 사과를 담는데 필요한 바구니의 수
문제의 결과  값은 정답이지만 
사과 의 수가 변경될 수도 있다고 가정한다면 예를 들어 사과의 수가 120개 로 바뀐다면 
필요없는 바구니가 생성되겠죠?? 한번 고려해보시면 좋을 것 같아요!

2023-01-19 06:36 UTC, beatitudo331 commented on src/leeDoGyeong/report2/Report2_6.java
> +        float celcius = (float) (Math.round((float) (fahrenheit - 32)*5/9 *100)/100.0);
Math.round() 함수를 사용하지 않고 처리할 것! .ㅠㅠ
괜찮슴다! 이따 같이 봐요!

2023-01-21 04:53 UTC, colleenInKorea commented on src/leeDoGyeong/report2/Report2_4.java
> +        int numOfBucket = ((numOfApples/sizeOfBucket) + 1); // 모든 사과를 담는데 필요한 바구니의 수
알겠습니다 :)

2023-02-08 06:28 UTC, closed without merging